var appleImages = [
  {
    name: "Apple #1",
    id: "Apple1",
    alt: "Apple1",
    location: "./img/apple/Apple1.jpg",
    copyright: "",
  },
  {
    name: "Apple #2",
    id: "Apple2",
    alt: "Apple2",
    location: "./img/apple/Apple2.jpg",
    copyright: "",
  },
  {
    name: "Apple #3",
    id: "Apple3",
    alt: "Apple3",
    location: "./img/apple/Apple3.jpg",
    copyright: "",
  },
  {
    name: "Apple #4",
    id: "Apple4",
    alt: "Apple4",
    location: "./img/apple/Apple4.jpg",
    copyright: "",
  },
  {
    name: "Apple #5",
    id: "Apple5",
    alt: "Apple5",
    location: "./img/apple/Apple5.jpg",
    copyright: "",
  },
  {
    name: "Apple #6",
    id: "Apple6",
    alt: "Apple6",
    location: "./img/apple/Apple6.jpg",
    copyright: "",
  },
  {
    name: "Apple #7",
    id: "Apple7",
    alt: "Apple7",
    location: "./img/apple/Apple7.jpg",
    copyright: "",
  },
  {
    name: "Apple #8",
    id: "Apple8",
    alt: "Apple8",
    location: "./img/apple/Apple8.jpg",
    copyright: "",
  },
  {
    name: "Apple #9",
    id: "Apple9",
    alt: "Apple9",
    location: "./img/apple/Apple9.jpg",
    copyright: "",
  },
  {
    name: "Apple #10",
    id: "Apple10",
    alt: "Apple10",
    location: "./img/apple/Apple10.jpg",
    copyright: "",
  },
  {
    name: "Apple #11",
    id: "Apple11",
    alt: "Apple11",
    location: "./img/apple/Apple11.jpg",
    copyright: "",
  },
  {
    name: "Apple #12",
    id: "Apple12",
    alt: "Apple12",
    location: "./img/apple/Apple12.jpg",
    copyright: "",
  },
];
var cattleImages = [
  {
    name: "Bruce",
    id: "Cattle1",
    alt: "Cattle1",
    location: "./img/cattle/cattle1.jpg",
    copyright: "agriflanders, CC BY 2.0",
  },
  {
    name: "Nidal",
    id: "Cattle2",
    alt: "Cattle2",
    location: "./img/cattle/cattle2.jpg",
    copyright: "Nidal Shbeeb",
  },
  {
    name: "Dolly",
    id: "Cattle3",
    alt: "Cattle3",
    location: "./img/cattle/cattle3.jpg",
    copyright: "Chris Embry Mohr",
  },
  {
    name: "Boss",
    id: "Cattle4",
    alt: "Cattle4",
    location: "./img/cattle/cattle4.jpg",
    copyright: "Jud Parker. Rights Reserved.",
  },
  {
    name: "Tuffy",
    id: "Cattle5",
    alt: "Cattle5",
    location: "./img/cattle/cattle5.jpg",
    copyright: "",
  },
  {
    name: "Job",
    id: "Cattle6",
    alt: "Cattle6",
    location: "./img/cattle/cattle6.jpg",
    copyright: "George Hodan",
  },
  {
    name: "Quasimodo",
    id: "Cattle7",
    alt: "Cattle7",
    location: "./img/cattle/cattle7.jpg",
    copyright:
      "Department of Animal and Food Sciences, Oklahoma State University",
  },
  {
    name: "Curly",
    id: "Cattle8",
    alt: "Cattle8",
    location: "./img/cattle/cattle8.jpg",
    copyright: "emdot, CC BY 2.0, digitally altered    ",
  },
  {
    name: "Milestone",
    id: "Cattle9",
    alt: "Cattle9",
    location: "./img/cattle/cattle9.jpg",
    copyright: "Wright Charolais",
  },
  {
    name: "Mudhorn",
    id: "Cattle10",
    alt: "Cattle10",
    location: "./img/cattle/cattle10.jpg",
    copyright:
      "Kyle Kehrli & Wilbur Kehrli, American Blue Cattle Breeders. Rights reserved.",
  },
  {
    name: "Lady",
    id: "Cattle11",
    alt: "Cattle11",
    location: "./img/cattle/cattle11.jpg",
    copyright:
      "Kyle Kehrli & Wilbur Kehrli, American Blue Cattle Breeders. Rights reserved.",
  },
  {
    name: "Natale",
    id: "Cattle12",
    alt: "Cattle12",
    location: "./img/cattle/cattle12.jpg",
    copyright: "Vito Natale",
  },
  {
    name: "Carmel",
    id: "Cattle13",
    alt: "Cattle13",
    location: "./img/cattle/cattle13.jpg",
    copyright: "Chris Embry Mohr",
  },
  {
    name: "Ankole",
    id: "Cattle14",
    alt: "Cattle14",
    location: "./img/cattle/cattle14.jpg",
    copyright: "La Doroda Brigadoon (FP748) by Elizabeth Lundgren",
  },
  {
    name: "Seurat",
    id: "Cattle15",
    alt: "Cattle15",
    location: "./img/cattle/cattle15.jpg",
    copyright: "Dickinson Cattle Co.",
  },
  {
    name: "Wink",
    id: "Cattle16",
    alt: "Cattle16",
    location: "./img/cattle/cattle16.jpg",
    copyright: "Jud Parker. Rights Reserved",
  },
  {
    name: "Integrity",
    id: "Cattle17",
    alt: "Cattle17",
    location: "./img/cattle/cattle17.jpg",
    copyright: "LIC Europe",
  },
  {
    name: "Daisy",
    id: "Cattle18",
    alt: "Cattle18",
    location: "./img/cattle/cattle18.jpg",
    copyright: "Chris Embry Mohr",
  },
  {
    name: "Chrissy",
    id: "Cattle19",
    alt: "Cattle19",
    location: "./img/cattle/cattle19.jpg",
    copyright: "JackieLou DL",
  },
  {
    name: "Samoa",
    id: "Cattle20",
    alt: "Cattle20",
    location: "./img/cattle/cattle20.jpg",
    copyright: "Taras Kasich",
  },
  {
    name: "Yukia",
    id: "Cattle21",
    alt: "Cattle21",
    location: "./img/cattle/cattle21.jpg",
    copyright:
      "Kyle Kehrli & Wilbur Kehrli, American Blue Cattle Breeders. Rights reserved.",
  },
  {
    name: "Elena",
    id: "Cattle22",
    alt: "Cattle22",
    location: "./img/cattle/cattle22.jpg",
    copyright: "Yvonne Huijbens",
  },
  {
    name: "Sammy",
    id: "Cattle23",
    alt: "Cattle23",
    location: "./img/cattle/cattle23.jpg",
    copyright: "dendoktoor",
  },
  {
    name: "Sunflower",
    id: "Cattle24",
    alt: "Cattle24",
    location: "./img/cattle/cattle24.jpg",
    copyright: "Screenroad",
  },
  {
    name: "Atlas",
    id: "Cattle25",
    alt: "Cattle25",
    location: "./img/cattle/cattle25.jpg",
    copyright: "Hilde Demeester",
  },
  {
    name: "Brownie",
    id: "Cattle26",
    alt: "Cattle26",
    location: "./img/cattle/cattle26.jpg",
    copyright: "Vedat Kandemir",
  },
  {
    name: "Hagrid",
    id: "Cattle27",
    alt: "Cattle27",
    location: "./img/cattle/cattle27.jpg",
    copyright: "rob walsh",
  },
  {
    name: "Dragon",
    id: "Cattle28",
    alt: "Cattle28",
    location: "./img/cattle/cattle28.jpg",
    copyright: "Zdeněk Macháček",
  },
  {
    name: "Harry",
    id: "Cattle29",
    alt: "Cattle29",
    location: "./img/cattle/cattle29.jpg",
    copyright: "pen_ash",
  },
  {
    name: "Zeus",
    id: "Cattle30",
    alt: "Cattle30",
    location: "./img/cattle/cattle30.jpg",
    copyright: "AStoKo",
  },
];

var tulipImages = [
  {
    name: "Tulip #1",
    id: "Tulip1",
    alt: "Tulip1",
    location: "./img/tulip/tulip1.jpg",
    copyright: "",
  },
  {
    name: "Tulip #2",
    id: "Tulip2",
    alt: "Tulip2",
    location: "./img/tulip/tulip2.jpg",
    copyright: "",
  },
  {
    name: "Tulip #3",
    id: "Tulip3",
    alt: "Tulip3",
    location: "./img/tulip/tulip3.jpg",
    copyright: "",
  },
  {
    name: "Tulip #4",
    id: "Tulip4",
    alt: "Tulip4",
    location: "./img/tulip/tulip4.jpg",
    copyright: "",
  },
  {
    name: "Tulip #5",
    id: "Tulip5",
    alt: "Tulip5",
    location: "./img/tulip/tulip5.jpg",
    copyright: "",
  },
  {
    name: "Tulip #6",
    id: "Tulip6",
    alt: "Tulip6",
    location: "./img/tulip/tulip6.jpg",
    copyright: "",
  },
  {
    name: "Tulip #7",
    id: "Tulip7",
    alt: "Tulip7",
    location: "./img/tulip/tulip7.jpg",
    copyright: "",
  },
  {
    name: "Tulip #8",
    id: "Tulip8",
    alt: "Tulip8",
    location: "./img/tulip/tulip8.jpg",
    copyright: "",
  },
  {
    name: "Tulip #9",
    id: "Tulip9",
    alt: "Tulip9",
    location: "./img/tulip/tulip9.jpg",
    copyright: "",
  },
  {
    name: "Tulip #10",
    id: "Tulip10",
    alt: "Tulip10",
    location: "./img/tulip/tulip10.jpg",
    copyright: "",
  },
  {
    name: "Tulip #11",
    id: "Tulip11",
    alt: "Tulip11",
    location: "./img/tulip/tulip11.jpg",
    copyright: "",
  },
  {
    name: "Tulip #12",
    id: "Tulip12",
    alt: "Tulip12",
    location: "./img/tulip/tulip12.jpg",
    copyright: "",
  },
  {
    name: "Tulip #13",
    id: "Tulip13",
    alt: "Tulip13",
    location: "./img/tulip/tulip13.jpg",
    copyright: "",
  },
  {
    name: "Tulip #14",
    id: "Tulip14",
    alt: "Tulip14",
    location: "./img/tulip/tulip14.jpg",
    copyright: "",
  },
  {
    name: "Tulip #15",
    id: "Tulip15",
    alt: "Tulip15",
    location: "./img/tulip/tulip15.jpg",
    copyright: "",
  },
  {
    name: "Tulip #16",
    id: "Tulip16",
    alt: "Tulip16",
    location: "./img/tulip/tulip16.jpg",
    copyright: "",
  },
  {
    name: "Tulip #17",
    id: "Tulip17",
    alt: "Tulip17",
    location: "./img/tulip/tulip17.jpg",
    copyright: "",
  },
  {
    name: "Tulip #18",
    id: "Tulip18",
    alt: "Tulip18",
    location: "./img/tulip/tulip18.jpg",
    copyright: "",
  },
  {
    name: "Tulip #19",
    id: "Tulip19",
    alt: "Tulip19",
    location: "./img/tulip/tulip19.jpg",
    copyright: "",
  },
  {
    name: "Tulip #20",
    id: "Tulip20",
    alt: "Tulip20",
    location: "./img/tulip/tulip20.jpg",
    copyright: "",
  },
  {
    name: "Tulip #21",
    id: "Tulip21",
    alt: "Tulip21",
    location: "./img/tulip/tulip21.jpg",
    copyright: "",
  },
  {
    name: "Tulip #22",
    id: "Tulip22",
    alt: "Tulip22",
    location: "./img/tulip/tulip22.jpg",
    copyright: "",
  },
  {
    name: "Tulip #23",
    id: "Tulip23",
    alt: "Tulip23",
    location: "./img/tulip/tulip23.jpg",
    copyright: "",
  },
  {
    name: "Tulip #24",
    id: "Tulip24",
    alt: "Tulip24",
    location: "./img/tulip/tulip24.jpg",
    copyright: "",
  },
];

export var newVariation = {
  name: "",
  images: [],
};
var appleTraits = [
  {
    id: "apple0",
    displayName: "Apples",
    downloadImage: "./img/apple/AppleCard.png",
    name: "",
    maxVariations: 6,
    details: {
      gallery: appleImages,
      variations: [newVariation],
    },
  },
];
var cattleTraits = [
  {
    id: "cattle0",
    displayName: "Cattle",
    downloadImage: "./img/cattle/CattleCard.png",
    name: "",
    maxVariations: 6,
    details: {
      gallery: cattleImages,
      variations: [newVariation],
    },
  },
];

var tulipTraits = [
  {
    id: "tulip1",
    displayName: "Tulip",
    downloadImage: "./img/cattle/CattleCard.png",
    name: "",
    maxVariations: 6,
    details: {
      gallery: tulipImages,
      variations: [newVariation],
    },
  },
];

export {
  cattleTraits,
  tulipTraits,
  appleTraits,
  cattleImages,
  tulipImages,
  appleImages,
};
